app:
  security:
    publicUrls: /user/register,/user/login,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/memory-status
    issuer: pare-app
    secretKey: testeste
    tokenExpirationMinutes: 10

# jpa properties
spring:

  jpa:
#    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
#      show_sql: true
#      format_sql: true
#      generate_statistics: true
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://google/pareapp?cloudSqlInstance=maximal-yew-347818:southamerica-east1:pareapp-prd&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=postgres

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        stat: DEBUG
#        type: TRACE
