app:
  security:
    publicUrls: /user/register,/user/login,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html
    issuer: pare-app
    secretKey: ${SECRET_KEY}
    tokenExpirationMinutes: 10

# jpa properties
spring:
  jpa:
#    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
#      show_sql: true
#      format_sql: true
#      generate_statistics: true
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        stat: DEBUG
#        type: TRACE
